################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
Full_Demo/Minimal/AbortDelay.obj: ../Full_Demo/Minimal/AbortDelay.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/AbortDelay.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/BlockQ.obj: ../Full_Demo/Minimal/BlockQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/BlockQ.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/EventGroupsDemo.obj: ../Full_Demo/Minimal/EventGroupsDemo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/EventGroupsDemo.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/GenQTest.obj: ../Full_Demo/Minimal/GenQTest.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/GenQTest.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/IntQueue.obj: ../Full_Demo/Minimal/IntQueue.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/IntQueue.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/IntSemTest.obj: ../Full_Demo/Minimal/IntSemTest.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/IntSemTest.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/MessageBufferAMP.obj: ../Full_Demo/Minimal/MessageBufferAMP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/MessageBufferAMP.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/MessageBufferDemo.obj: ../Full_Demo/Minimal/MessageBufferDemo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/MessageBufferDemo.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/PollQ.obj: ../Full_Demo/Minimal/PollQ.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/PollQ.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/QPeek.obj: ../Full_Demo/Minimal/QPeek.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/QPeek.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/QueueOverwrite.obj: ../Full_Demo/Minimal/QueueOverwrite.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/QueueOverwrite.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/QueueSet.obj: ../Full_Demo/Minimal/QueueSet.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/QueueSet.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/QueueSetPolling.obj: ../Full_Demo/Minimal/QueueSetPolling.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/QueueSetPolling.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/StaticAllocation.obj: ../Full_Demo/Minimal/StaticAllocation.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/StaticAllocation.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/StreamBufferDemo.obj: ../Full_Demo/Minimal/StreamBufferDemo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/StreamBufferDemo.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/StreamBufferInterrupt.obj: ../Full_Demo/Minimal/StreamBufferInterrupt.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/StreamBufferInterrupt.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/TaskNotify.obj: ../Full_Demo/Minimal/TaskNotify.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/TaskNotify.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/TimerDemo.obj: ../Full_Demo/Minimal/TimerDemo.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/TimerDemo.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/blocktim.obj: ../Full_Demo/Minimal/blocktim.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/blocktim.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/comtest.obj: ../Full_Demo/Minimal/comtest.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/comtest.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/countsem.obj: ../Full_Demo/Minimal/countsem.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/countsem.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/crflash.obj: ../Full_Demo/Minimal/crflash.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/crflash.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/death.obj: ../Full_Demo/Minimal/death.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/death.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/dynamic.obj: ../Full_Demo/Minimal/dynamic.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/dynamic.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/flash_timer.obj: ../Full_Demo/Minimal/flash_timer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/flash_timer.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/integer.obj: ../Full_Demo/Minimal/integer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/integer.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/recmutex.obj: ../Full_Demo/Minimal/recmutex.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/recmutex.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/semtest.obj: ../Full_Demo/Minimal/semtest.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/semtest.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Full_Demo/Minimal/sp_flop.obj: ../Full_Demo/Minimal/sp_flop.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="Full_Demo/Minimal/sp_flop.d" --obj_directory="Full_Demo/Minimal" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


