################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
FreeRTOS_Source/croutine.obj: ../FreeRTOS_Source/croutine.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/croutine.d" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/event_groups.obj: ../FreeRTOS_Source/event_groups.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/event_groups.d" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/list.obj: ../FreeRTOS_Source/list.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/list.d" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/queue.obj: ../FreeRTOS_Source/queue.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/queue.d" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/stream_buffer.obj: ../FreeRTOS_Source/stream_buffer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/stream_buffer.d" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/tasks.obj: ../FreeRTOS_Source/tasks.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/tasks.d" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS_Source/timers.obj: ../FreeRTOS_Source/timers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP432 Compiler'
	"C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -O0 --opt_for_speed=2 --include_path="C:/ti/ccsv6/ccs_base/arm/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/Minimal/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo/FreeRTOS_CLI" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Functions" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/Full_Demo" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib/inc" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/driverlib" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/include" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS/FreeRTOS_Source/portable/CCS/ARM_CM4F" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include" --include_path="C:/ti/ccsv6/tools/compiler/arm_15.12.3.LTS/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/" --include_path="C:/ti/ccsv6/ccs_base/arm/include/CMSIS" --include_path="C:/Users/cui16/Desktop/Code/NUEDC2019/MSP432_FreeRTOS" -g --gcc --define=__MSP432P401R__ --define=USE_CMSIS_REGISTER_FORMAT=1 --define=TARGET_IS_MSP432P4XX --define=ccs --verbose_diagnostics --diag_wrap=off --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="FreeRTOS_Source/timers.d" --obj_directory="FreeRTOS_Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


